version: '2.1'
services:
  homeassistant:
    container_name: homeassistant
    image: lscr.io/linuxserver/homeassistant
    network_mode: host
    privileged: true
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - ./homeassistant/data:/config

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    user: 1000:1000
    network_mode: host
    restart: unless-stopped
    # Note: mosquitto not respecting user/group option and all assets are created as root
    # Manually change these to appropriate user:group after initial start
    # `sudo chown -R 1000:1000 ./mosquitto` from within the parent directory 
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/data:/mosquitto/data

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    depends_on: 
      - mosquitto
    user: 1000:1000
    ports: 
      - 8080:8080
    restart: unless-stopped
    group_add:
      - dialout
      - uucp
      - tty
    environment:
      - TZ=Australia/Melbourne
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2486822-if00:/dev/ttyACM0

  nodered:
    container_name: nodered
    image: nodered/node-red
    depends_on:
      - homeassistant
      - mosquitto
    ports: 
      - "1880:1880/tcp"
    restart: unless-stopped
    environment:
      - TZ=Australia/Melbourne
    volumes:
      - ./nodered/data:/data

  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=vtGv6p&fa8EXcR^wqecAYlne
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    container_name: grafana
    image: teslamate/grafana:latest
    ports: 
      - 3000:3000
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=vtGv6p&fa8EXcR^wqecAYlne
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  teslamate:
    container_name: teslamate
    image: teslamate/teslamate:latest
    depends_on: 
      - postgres
      - grafana
    ports: 
      - 4000:4000
    restart: always
    cap_drop:
      - all
    environment:
      - ENCRYPTION_KEY=aaE3!m#DEbS&A8cDWKHK4*v@
      - DATABASE_USER=teslamate
      - DATABASE_PASS=vtGv6p&fa8EXcR^wqecAYlne
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=192.168.50.104
      - MQTT_PORT=1883
      - MQTT_USERNAME=hass
      - MQTT_PASSWORD=Granular747
    volumes:
      - ./import:/opt/app/import

volumes:
  teslamate-db:
  teslamate-grafana-data:  
